import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

// Usage
// npx tsx prisma/seed-types.ts

async function main() {
  // Most common scam types
  const scamTypes = [
    // ...existing types...
    "Fake Tech Support",
    "Crypto Investment Scam",
    "Romance Scam",
    "Online Shopping Scam",
    "Rental Scam",
    "Government Impersonation",
    "Lottery Scam",
    "Charity Scam",
    "Employment Scam",
    "Phishing (Email/SMS)",
    "Social Media Scam",
    "Fake Website",
    "Advance Fee Fraud",
    "Business Email Compromise",
    "Impersonation Scam",
    "Investment Scam",
    "Fake Invoices",
    "Utility Scam",
    "Travel Scam",
    "Medical Scam",
    "Courier Fraud",
    "Banking Scam",
    "HMRC Scam",
    "PayPal Scam",
    "Amazon Scam",
    "eBay Scam",
    "Facebook Marketplace Scam",
    "WhatsApp Scam",
    "Instagram Scam",
    "Fake Delivery Scam",
    "Mobile Phone Scam",
    "Pension Scam",
    "Ticket Scam",
    "Loan Scam",
    "Insurance Scam",
    "Fake Charity Collection",
    "Fake Police Scam",
    "Fake Bailiff Scam",
    "Fake Solicitor Scam",
    "Fake Job Offer",
    "Fake Rental Property",
    "Fake Investment Opportunity",
    "Fake Prize Draw",
    "Fake Survey Scam",
    "Fake Refund Scam",
    "Fake Tax Rebate",
    "Fake Bank Call",
    "Fake Bank Email",
    "Fake Bank Text",
    "Fake Utility Bill",
    "Fake Council Tax",
    "Fake NHS Scam",
    "Fake TV Licence",
    "Fake DVLA Scam",
    "Fake Parcel Delivery",
    "Fake Dating Profile",
    "Fake Pet Sale",
    "Fake Holiday Rental",
    "Fake Charity Appeal",
    "Fake Invoice",
    "Fake Subscription",
    "Fake Subscription Trap",
    "Fake Debt Collection",
    "Fake Investment Platform",
    "Fake Cryptocurrency",
    "Fake Trading Platform",
    "Fake Loan Offer",
    "Fake Grant Offer",
    "Fake Compensation Offer",
    "Fake Legal Threat",
    "Fake Immigration Scam",
    "Fake Student Loan",
    "Fake Scholarship",
    "Fake University Offer",
    "Fake Exam Fee",
    "Fake School Fee",
    "Fake Utility Provider",
    "Fake Broadband Provider",
    "Fake Mobile Provider",
    "Fake Tech Gadget",
    "Fake Concert Ticket",
    "Fake Sporting Event Ticket",
    "Fake Airline Ticket",
    "Fake Hotel Booking",
    "Fake Car Sale",
    "Fake Vehicle Logbook",
    "Fake MOT",
    "Fake Car Insurance",
    "Fake Breakdown Cover",
    "Fake Parking Fine",
    "Fake Charity Shop",
    "Fake Fundraiser",
    "Fake Crowdfunding",
    "Fake GoFundMe",
    "Fake JustGiving",
    "Fake eBay Buyer",
    "Fake eBay Seller",
    "Fake Gumtree Listing",
    "Fake Shpock Listing",
    "Fake Vinted Listing",
    "Fake Depop Listing",
    "Fake Amazon Seller",
    "Fake Amazon Buyer",
    // Non-online and physical scams
    "Pickpocketing",
    "ATM Skimming",
    "Card Cloning",
    "Cheque Fraud",
    "Counterfeit Money",
    "Distraction Theft",
    "Bag Snatching",
    "Purse Snatching",
    "Shoulder Surfing",
    "Fake Charity Collector",
    "Fake Utility Worker",
    "Fake Police Officer",
    "Fake Delivery Person",
    "Fake Repairman",
    "Fake Surveyor",
    "Fake Inspector",
    "Fake Landlord",
    "Fake Tenant",
    "Fake Buyer",
    "Fake Seller",
    "Fake Contractor",
    "Fake Builder",
    "Fake Plumber",
    "Fake Electrician",
    "Fake Locksmith",
    "Fake Cleaner",
    "Fake Gardener",
    "Fake Pet Breeder",
    "Fake Vet",
    "Fake Doctor",
    "Fake Nurse",
    "Fake Pharmacist",
    "Fake Ambulance",
    "Fake Firefighter",
    "Fake Security Guard",
    "Fake Event Staff",
    "Fake Ticket Seller",
    "Fake Parking Attendant",
    "Fake Taxi Driver",
    "Fake Ride Share",
    "Fake Moving Company",
    "Fake Storage Company",
    "Fake Auctioneer",
    "Fake Antique Dealer",
    "Fake Jeweler",
    "Fake Art Dealer",
    "Fake Estate Agent",
    "Fake Survey Scam",
    "Fake Prize Scam",
    "Fake Raffle Scam",
    "Fake Charity Scam",
    "Fake Fundraiser Scam",
    "Fake Crowdfunding Scam",
    "Fake GoFundMe Scam",
    "Fake JustGiving Scam",
    "Fake eBay Scam",
    "Fake Gumtree Scam",
    "Fake Shpock Scam",
    "Fake Vinted Scam",
    "Fake Depop Scam",
    "Fake Amazon Scam",
    "Fake Buyer Scam",
    "Fake Seller Scam",
    "Fake Tenant Scam",
    "Fake Landlord Scam",
    "Fake Contractor Scam",
    "Fake Builder Scam",
    "Fake Plumber Scam",
    "Fake Electrician Scam",
    "Fake Locksmith Scam",
    "Fake Cleaner Scam",
    "Fake Gardener Scam",
    "Fake Pet Breeder Scam",
    "Fake Vet Scam",
    "Fake Doctor Scam",
    "Fake Nurse Scam",
    "Fake Pharmacist Scam",
    "Fake Ambulance Scam",
    "Fake Firefighter Scam",
    "Fake Security Guard Scam",
    "Fake Event Staff Scam",
    "Fake Ticket Seller Scam",
    "Fake Parking Attendant Scam",
    "Fake Taxi Driver Scam",
    "Fake Ride Share Scam",
    "Fake Moving Company Scam",
    "Fake Storage Company Scam",
    "Fake Auctioneer Scam",
    "Fake Antique Dealer Scam",
    "Fake Jeweler Scam",
    "Fake Art Dealer Scam",
    "Fake Estate Agent Scam",
    "Theft",
    "Robbery",
    "Burglary",
    "Shoplifting",
    "Pickpocketing",
    "ATM Fraud",
    "Cheque Fraud",
    "Counterfeit Goods",
    "Counterfeit Tickets",
    "Counterfeit Documents",
    "Other (not on the list)",
  ];

  for (const name of scamTypes) {
    try {
      await prisma.scamType.upsert({
        where: { name },
        update: {},
        create: {
          name,
          isApproved: true,
          isUserCreated: false,
        },
      });
      console.log(`✓ Processed: ${name}`);
    } catch (error) {
      console.error(`✗ Error with ${name}:`, error);
    }
  }

  console.log("\nSeed completed! Checking results...");

  const totalCount = await prisma.scamType.count();
  const approvedCount = await prisma.scamType.count({
    where: { isApproved: true },
  });

  console.log(`Total scam types: ${totalCount}`);
  console.log(`Approved scam types: ${approvedCount}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
